/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: ExampleIdlData.idl
  Source: ExampleIdlData.cpp
  Cyclone DDS: v0.9.0

*****************************************************************/
#include "ExampleIdlData.hpp"

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
entity_properties_t get_type_props<::ExampleIdlData::Msg>() {
  static std::mutex mtx;
  static entity_properties_t props;
  static bool initialized = false;

  if (initialized)
    return props;

  std::lock_guard<std::mutex> lock(mtx);
  props.clear();
  key_endpoint keylist;

  props.m_members_by_seq.push_back(entity_properties_t(0,false));
  props.m_members_by_seq.back().e_bb = bb_32_bits;
  keylist.add_key_endpoint(std::list<uint32_t>{0});
  props.m_members_by_seq.push_back(entity_properties_t(1,false));
  props.m_members_by_seq.push_back(entity_properties_t(2,false));
  props.m_members_by_seq.back().e_bb = bb_8_bits;
  props.m_members_by_seq.push_back(entity_properties_t(3,false));
  props.m_members_by_seq.back().e_bb = bb_8_bits;
  props.m_members_by_seq.push_back(entity_properties_t(4,false));
  props.m_members_by_seq.back().e_bb = bb_8_bits;
  props.m_members_by_seq.push_back(final_entry());
  props.m_keys.push_back(final_entry());
  props.finish(keylist);
  initialized = true;
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

